language: php

php:
  - 5.4
  - 5.5

script:
  - vendor/bin/codecept build
  - vendor/bin/codecept run unit

before_script:
  - mv app/Config/Config.php.example app/Config/Config.php
  - wget http://getcomposer.org/composer.phar
  - php composer.phar self-update
  - php composer.phar install